/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rationem.entity.document;

//import com.rationem.entity.audit.AuditDocLine;
import com.rationem.entity.cm.Contact;
import com.rationem.entity.config.company.PostType;
import com.rationem.entity.user.User;
import java.util.List;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.UniqueConstraint;
import javax.persistence.JoinColumn;
import javax.persistence.Version;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.Temporal;
import javax.persistence.Inheritance;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import com.rationem.entity.config.common.LineTypeRule;
import com.rationem.entity.fi.company.CompanyBasic;
import com.rationem.entity.salesTax.vat.VatCodeCompany;
import com.rationem.entity.salesTax.vat.VatReturnLine;
import com.rationem.entity.tr.bank.BnkPaymentRun;
import java.util.ArrayList;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorValue;
import javax.persistence.SequenceGenerator;
import org.eclipse.persistence.annotations.Multitenant;
import org.eclipse.persistence.annotations.TenantDiscriminatorColumn;

import static org.eclipse.persistence.annotations.MultitenantType.SINGLE_TABLE;


import static javax.persistence.TemporalType.TIMESTAMP;
import static javax.persistence.TemporalType.DATE;
import static javax.persistence.InheritanceType.JOINED;
import static javax.persistence.DiscriminatorType.STRING;



/**
 *
 * @author Chris
 */
@Entity
@Inheritance(strategy=JOINED )
@DiscriminatorColumn(name="DTYPE",discriminatorType=STRING,length=50)
@DiscriminatorValue("document.DocLineBase")
@Table(name="doc_line01" , uniqueConstraints = @UniqueConstraint(columnNames =  {
    "doc_id", "line_num"         }
))
@NamedQueries({
 @NamedQuery(name="allOslines", query="select d from DocLineBase d where  d.clearedByLine is null"),
 @NamedQuery(name="doc4Line", query="Select distinct l.docHeaderBase from DocLineBase l where l.id = :lineId"),
 @NamedQuery(name="linesForFiscPer", query="Select l from DocLineBase l  "),
 @NamedQuery(name="lines4Doc",query="select l from DocLineBase l where l.docHeaderBase.id = :docId ")
})
@SequenceGenerator(name = "docLine_s1", sequenceName = "docLIne01_s1", allocationSize = 1,initialValue=1)
@Multitenant(SINGLE_TABLE)
@TenantDiscriminatorColumn(name="tenant_id",discriminatorType=STRING,length=50, contextProperty="tenantId")
public class DocLineBase implements Serializable {

  
 private static final long serialVersionUID = 1L;
 @Id
 @GeneratedValue(generator = "docLine_s1")
 @Column(name="doc_line_id")
 private Long id;
 @Column(name="doc_num")
 private Long docNumber;
 @Column(name="line_num")
 private Long lineNum;
 @Column(name="created_on")
 @Temporal(TIMESTAMP)
 private Date createDate;
 @ManyToOne
 @JoinColumn(name="created_by_id", referencedColumnName="partner_id")
 private User createBy;
 @Column(name="changed_on")
 @Temporal(TIMESTAMP)
 private Date changeDate;
 @ManyToOne
 @JoinColumn(name="changed_by_id", referencedColumnName="partner_id")
 private User changeBy;
 @Column(name="changes")
 @Version
 private int revision;
 
 @ManyToOne
 @JoinColumn(name="bnk_pay_run_id", referencedColumnName="bank_pay_run_id")
 private BnkPaymentRun bnkPaymentRun;
 
 
 @OneToOne
 @JoinColumn(name="bank_trans_id", referencedColumnName="bank_trans_id")
 private DocBankLineBase bankLine;
 
 @OneToMany(mappedBy = "docLine")
 private List<Contact> contacts;
 
    //private String docCurrCode;
    //private double docAmount;
 @Column(name="home_amount")
 private double homeAmount;
 @Column(name="original_amount")
 private double orginalAmount;
 @Column(name="paid_amount")
 private double paidAmount;
 @Column(name="line_text")
 private String lineText;
 @Column(name="sort_order")
 private String sortOrder;
    /**
     * Reference 1 for adhoc use by user
     */
 @Column(name="ref1")
 private String reference1;
    /**
     * Reference 2 for adhoc use by user
     */
 @Column(name="ref2")
 private String reference2;
    
 @Column(name="line_notes")
 private String notes;
 @Column(name="auto_gen")
 private boolean autoGenerated;
 @Column(name="tax_amount")
 private double taxAmount;
    
 
 @OneToOne
 @JoinColumn(name="part_paid_Line_id", referencedColumnName="doc_line_id")
 private DocLineBase partPaymentLine;

 @OneToOne(mappedBy = "partPaymentLine")
 private DocLineBase originalLinePtpaid;
    
 @ManyToOne
 @JoinColumn(name="doc_id", referencedColumnName="doc_id" )
 private DocBase docHeaderBase;
 
 /*@ManyToOne
 @JoinColumn(name="doc_fi_id", referencedColumnName="doc_id" )
 private DocFI docFi;
 */
 
 @ManyToOne
 @JoinColumn(name="comp_id", referencedColumnName="home_comp_id")
 private CompanyBasic comp;

 @ManyToOne
 @JoinColumn(name="line_type_id", referencedColumnName="line_type_id")
 private LineTypeRule lineType;
 
    
 @ManyToOne
 @JoinColumn(name="vat_code_id", referencedColumnName="vat_code_comp_id")
 private VatCodeCompany vatCodeCompany;   

    /**
     * List of document lines cleared by this document line
     *
     */
 @OneToMany(mappedBy = "clearedByLine")
 private List<DocLineBase> clearingLineForLines;

    /**
     * This document is cleared by document id clearedByLine
     */
 @ManyToOne
 @JoinColumn(name="cleared_by_line_id", referencedColumnName="doc_line_id")
 private DocLineBase clearedByLine;
    
 @Column(name="cleared")
 private boolean clearedLine;
 @Column(name="clearing")
 private boolean clearingLine;
    
 @Temporal(DATE)
 @Column(name="clearing_date")
 private Date clearingDate;

 @ManyToOne
 @JoinColumn(name="post_type_id",referencedColumnName="post_type_id")
 private PostType postType;

 @OneToMany(mappedBy = "fiDocLine")
    private List<VatReturnLine> vatReturnLines;


 public Long getId() {
  return id;
 }

 public void setId(Long id) {
  this.id = id;
 }

 public Long getLineNum() {
  return lineNum;
 }

 public void setLineNum(Long lineNum) {
  this.lineNum = lineNum;
 }

 public Date getCreateDate() {
  return createDate;
 }

 public void setCreateDate(Date createDate) {
  this.createDate = createDate;
 }

 public User getCreateBy() {
  return createBy;
 }

 public void setCreateBy(User createBy) {
  this.createBy = createBy;
 }

 public Date getChangeDate() {
  return changeDate;
 }

 public void setChangeDate(Date changeDate) {
  this.changeDate = changeDate;
 }

 public User getChangeBy() {
  return changeBy;
 }

 public void setChangeBy(User changeBy) {
  this.changeBy = changeBy;
 }

 public int getRevision() {
  return revision;
 }

 public void setRevision(int revision) {
  this.revision = revision;
 }

 public BnkPaymentRun getBnkPaymentRun() {
  return bnkPaymentRun;
 }

 public void setBnkPaymentRun(BnkPaymentRun bnkPaymentRun) {
  this.bnkPaymentRun = bnkPaymentRun;
 }

 public DocBankLineBase getBankLine() {
  return bankLine;
 }

 public void setBankLine(DocBankLineBase bankLine) {
  this.bankLine = bankLine;
 }

 
 public double getHomeAmount() {
  return homeAmount;
 }

 public void setHomeAmount(double homeAmount) {
  this.homeAmount = homeAmount;
 }

 public double getOrginalAmount() {
  return orginalAmount;
 }

 public void setOrginalAmount(double orginalAmount) {
  this.orginalAmount = orginalAmount;
 }

 public double getPaidAmount() {
  return paidAmount;
 }

 public void setPaidAmount(double paidAmount) {
  this.paidAmount = paidAmount;
 }

 public String getLineText() {
  return lineText;
 }

 public void setLineText(String lineText) {
  this.lineText = lineText;
 }

 

 public String getReference1() {
  return reference1;
 }

 public void setReference1(String reference1) {
  this.reference1 = reference1;
 }

 public String getReference2() {
  return reference2;
 }

 public void setReference2(String reference2) {
  this.reference2 = reference2;
 }

 public String getSortOrder() {
  return sortOrder;
 }

 public void setSortOrder(String sortOrder) {
  this.sortOrder = sortOrder;
 }

 public double getTaxAmount() {
  return taxAmount;
 }

 public void setTaxAmount(double taxAmount) {
  this.taxAmount = taxAmount;
 }
 
 
 public String getNotes() {
  return notes;
 }

 public void setNotes(String notes) {
  this.notes = notes;
 }

 public boolean isAutoGenerated() {
  return autoGenerated;
 }

 public void setAutoGenerated(boolean autoGenerated) {
  this.autoGenerated = autoGenerated;
 }

 public void addClearedLine(DocLineBase line){
  if(clearingLineForLines == null){
    clearingLineForLines = new ArrayList<>();
  }
  clearingLineForLines.add(line);
 }
 
 public DocLineBase getPartPaymentLine() {
  return partPaymentLine;
 }

 public void setPartPaymentLine(DocLineBase partPaymentLine) {
  this.partPaymentLine = partPaymentLine;
 }

 public DocLineBase getOriginalLinePtpaid() {
  return originalLinePtpaid;
 }

 public void setOriginalLinePtpaid(DocLineBase originalLinePtpaid) {
  this.originalLinePtpaid = originalLinePtpaid;
 }

 public List<Contact> getContacts() {
  return contacts;
 }

 public void setContacts(List<Contact> contacts) {
  this.contacts = contacts;
 }

 public DocBase getDocHeaderBase() {
  return docHeaderBase;
 }

 public void setDocHeaderBase(DocBase docHeaderBase) {
  this.docHeaderBase = docHeaderBase;
 }
 
 public DocBase getDocBase() {
        return docHeaderBase;
 }

 public void setDocBase(DocBase docBase) {
        this.docHeaderBase = docBase;
 }

 

 public Long getDocNumber() {
  return docNumber;
 }

 public void setDocNumber(Long docNumber) {
  this.docNumber = docNumber;
 }

 
 public CompanyBasic getComp() {
  return comp;
 }

 public void setComp(CompanyBasic comp) {
  this.comp = comp;
 }

 public LineTypeRule getLineType() {
  return lineType;
 }

 public void setLineType(LineTypeRule lineType) {
  this.lineType = lineType;
 }

 public List<DocLineBase> getClearingLineForLines() {
  return clearingLineForLines;
 }

 public void setClearingLineForLines(List<DocLineBase> clearingLineForLines) {
  this.clearingLineForLines = clearingLineForLines;
 }

 public DocLineBase getClearedByLine() {
  return clearedByLine;
 }

 public void setClearedByLine(DocLineBase clearedByLine) {
  this.clearedByLine = clearedByLine;
 }

 public boolean isClearedLine() {
  return clearedLine;
 }

 public void setClearedLine(boolean clearedLine) {
  this.clearedLine = clearedLine;
 }

 public boolean isClearingLine() {
  return clearingLine;
 }

 public void setClearingLine(boolean clearingLine) {
  this.clearingLine = clearingLine;
 }

 public Date getClearingDate() {
  return clearingDate;
 }

 public void setClearingDate(Date clearingDate) {
  this.clearingDate = clearingDate;
 }

 public PostType getPostType() {
  return postType;
 }

 public void setPostType(PostType postType) {
  this.postType = postType;
 }

 public VatCodeCompany getVatCodeCompany() {
  return vatCodeCompany;
 }

 public void setVatCodeCompany(VatCodeCompany vatCodeCompany) {
  this.vatCodeCompany = vatCodeCompany;
 }

 public List<VatReturnLine> getVatReturnLines() {
  return vatReturnLines;
 }

 public void setVatReturnLines(List<VatReturnLine> vatReturnLines) {
  this.vatReturnLines = vatReturnLines;
 }

 
 @Override
 public int hashCode() {
  int hash = 0;
  hash += (id != null ? id.hashCode() : 0);
  return hash;
 }

 @Override
 public boolean equals(Object object) {
  // TODO: Warning - this method won't work in the case the id fields are not set
  if (!(object instanceof DocLineBase)) {
   return false;
  }
  DocLineBase other = (DocLineBase) object;
  if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
   return false;
  }
  return true;
 }

 @Override
 public String toString() {
  return "com.rationem.entity.document.DocLineBase[ id=" + id + " ]";
 }
 
}
