/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rationem.busRec.doc;

import com.rationem.busRec.config.common.LineTypeRuleRec;
import com.rationem.busRec.config.company.PostTypeRec;
import com.rationem.busRec.fi.company.CompanyBasicRec;
import com.rationem.busRec.user.UserRec;
import com.rationem.busRec.salesTax.vat.VatCodeCompanyRec;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author user
 */
public class DocLineFiTemplateRec implements Serializable {
 
 private Long id;
 private DocFiTemplateBaseRec doc;
 private Long lineNum;
 private double homeAmount;
 private double orginalAmount;
 private double paidAmount;
 private String lineText;
 private String sortOrder;
 private String reference1;
 private String reference2;
 private String notes;
 private boolean autoGenerated;
 private boolean lazyLoaded;
 private CompanyBasicRec comp;

 private LineTypeRuleRec lineType;
    
 private VatCodeCompanyRec vatCode;
 private PostTypeRec postType;
 
 private Date createDate;
 private UserRec createBy;
 private Date changeDate;
 private UserRec changeBy;
 private int revision;

 public DocLineFiTemplateRec() {
 }

 public Long getId() {
  return id;
 }

 public void setId(Long id) {
  this.id = id;
 }

 public DocFiTemplateBaseRec getDoc() {
  return doc;
 }

 public void setDoc(DocFiTemplateBaseRec doc) {
  this.doc = doc;
 }
/**
 * Have the lazy components been loaded?
 * @return 
 */
 public boolean isLazyLoaded() {
  return lazyLoaded;
 }

 /**
  * Set lazy components as loaded
  * @param lazyLoaded 
  */
 public void setLazyLoaded(boolean lazyLoaded) {
  this.lazyLoaded = lazyLoaded;
 }

 public Long getLineNum() {
  return lineNum;
 }

 public void setLineNum(Long lineNum) {
  this.lineNum = lineNum;
 }

 public double getHomeAmount() {
  return homeAmount;
 }

 public void setHomeAmount(double homeAmount) {
  this.homeAmount = homeAmount;
 }

 public double getOrginalAmount() {
  return orginalAmount;
 }

 public void setOrginalAmount(double orginalAmount) {
  this.orginalAmount = orginalAmount;
 }

 public double getPaidAmount() {
  return paidAmount;
 }

 public void setPaidAmount(double paidAmount) {
  this.paidAmount = paidAmount;
 }

 public String getLineText() {
  return lineText;
 }

 public void setLineText(String lineText) {
  this.lineText = lineText;
 }

 public String getSortOrder() {
  return sortOrder;
 }

 public void setSortOrder(String sortOrder) {
  this.sortOrder = sortOrder;
 }

 public String getReference1() {
  return reference1;
 }

 public void setReference1(String reference1) {
  this.reference1 = reference1;
 }

 public String getReference2() {
  return reference2;
 }

 public void setReference2(String reference2) {
  this.reference2 = reference2;
 }

 public String getNotes() {
  return notes;
 }

 public void setNotes(String notes) {
  this.notes = notes;
 }

 public boolean isAutoGenerated() {
  return autoGenerated;
 }

 public void setAutoGenerated(boolean autoGenerated) {
  this.autoGenerated = autoGenerated;
 }

 public CompanyBasicRec getComp() {
  return comp;
 }

 public void setComp(CompanyBasicRec comp) {
  this.comp = comp;
 }

 public LineTypeRuleRec getLineType() {
  return lineType;
 }

 public void setLineType(LineTypeRuleRec lineType) {
  this.lineType = lineType;
 }

 public VatCodeCompanyRec getVatCode() {
  return vatCode;
 }

 public void setVatCode(VatCodeCompanyRec vatCode) {
  this.vatCode = vatCode;
 }

 public PostTypeRec getPostType() {
  return postType;
 }

 public void setPostType(PostTypeRec postType) {
  this.postType = postType;
 }

 public Date getCreateDate() {
  return createDate;
 }

 public void setCreateDate(Date createDate) {
  this.createDate = createDate;
 }

 public UserRec getCreateBy() {
  return createBy;
 }

 public void setCreateBy(UserRec createBy) {
  this.createBy = createBy;
 }

 public Date getChangeDate() {
  return changeDate;
 }

 public void setChangeDate(Date changeDate) {
  this.changeDate = changeDate;
 }

 public UserRec getChangeBy() {
  return changeBy;
 }

 public void setChangeBy(UserRec changeBy) {
  this.changeBy = changeBy;
 }

 public int getRevision() {
  return revision;
 }

 public void setRevision(int revision) {
  this.revision = revision;
 }

 
 
}
