/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rationem.busRec.doc;

import com.rationem.busRec.config.common.LineTypeRuleRec;
import com.rationem.busRec.config.company.PostTypeRec;
import com.rationem.busRec.fi.company.CompanyBasicRec;
import com.rationem.busRec.user.UserRec;
import com.rationem.busRec.salesTax.vat.VatCodeCompanyRec;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Chris
 */
public class DocLineBasePartialRec implements Serializable{
 
 private Long id;
    private Long lineNum;
    private Date createDate;
    private UserRec createBy;
    private Date changeDate;
    private UserRec changeBy;
    private int revision;
    
    
    private double docAmount;
    private double homeAmount;
    private double orginalAmount;
    private double paidAmount;
    private String lineText;
    private String sortOrder;
    private String debitValue;
    private String creditValue;
    private boolean reset;

    private DocBasePartialRec docHeaderBase;
    //LineTypeRule
    private LineTypeRuleRec lineType;
    /**
     * Posting type e.g. GL DR/CR
     */
    private PostTypeRec postType;
    /**
     * User reference 1
     */
    private String reference1;
    /**
     * User Reference 2
     */
    private String reference2;
    /**
     * List of Document lines cleared by the document line
     */
    private String notes;
    private boolean autoGenerated;
    private VatCodeCompanyRec vatCode;
    private List<DocLineBasePartialRec> clearingLineForLines;
    /**
     * Document line that clears this document line
     */
    private DocLineBasePartialRec clearedByLine;
    private boolean clearedLine;
    private boolean clearingLine;
    private Date clearingDate;
    
    private CompanyBasicRec comp;

 public DocLineBasePartialRec() {
 }

 public Long getId() {
  return id;
 }

 public void setId(Long id) {
  this.id = id;
 }

 public Long getLineNum() {
  return lineNum;
 }

 public void setLineNum(Long lineNum) {
  this.lineNum = lineNum;
 }

 public Date getCreateDate() {
  return createDate;
 }

 public void setCreateDate(Date createDate) {
  this.createDate = createDate;
 }

 public UserRec getCreateBy() {
  return createBy;
 }

 public void setCreateBy(UserRec createBy) {
  this.createBy = createBy;
 }

 public Date getChangeDate() {
  return changeDate;
 }

 public void setChangeDate(Date changeDate) {
  this.changeDate = changeDate;
 }

 public UserRec getChangeBy() {
  return changeBy;
 }

 public void setChangeBy(UserRec changeBy) {
  this.changeBy = changeBy;
 }

 public int getRevision() {
  return revision;
 }

 public void setRevision(int revision) {
  this.revision = revision;
 }

 

 public double getHomeAmount() {
  return homeAmount;
 }

 public void setHomeAmount(double homeAmount) {
  this.homeAmount = homeAmount;
 }

 public String getNotes() {
  return notes;
 }

 public void setNotes(String notes) {
  this.notes = notes;
 }

 public double getOrginalAmount() {
  return orginalAmount;
 }

 public void setOrginalAmount(double orginalAmount) {
  this.orginalAmount = orginalAmount;
 }

 public double getPaidAmount() {
  return paidAmount;
 }

 public void setPaidAmount(double paidAmount) {
  this.paidAmount = paidAmount;
 }

 public String getLineText() {
  return lineText;
 }

 public void setLineText(String lineText) {
  this.lineText = lineText;
 }

 public String getSortOrder() {
  return sortOrder;
 }

 public void setSortOrder(String sortOrder) {
  this.sortOrder = sortOrder;
 }

 public String getDebitValue() {
  return debitValue;
 }

 public void setDebitValue(String debitValue) {
  this.debitValue = debitValue;
 }

 public String getCreditValue() {
  return creditValue;
 }

 public void setCreditValue(String creditValue) {
  this.creditValue = creditValue;
 }

 public boolean isReset() {
  return reset;
 }

 public void setReset(boolean reset) {
  this.reset = reset;
 }

 public double getDocAmount() {
  return docAmount;
 }

 public void setDocAmount(double docAmount) {
  this.docAmount = docAmount;
 }

 public DocBasePartialRec getDocHeaderBase() {
  return docHeaderBase;
 }

 public void setDocHeaderBase(DocBasePartialRec docHeaderBase) {
  this.docHeaderBase = docHeaderBase;
 }

 public LineTypeRuleRec getLineType() {
  return lineType;
 }

 public void setLineType(LineTypeRuleRec lineType) {
  this.lineType = lineType;
 }

 public PostTypeRec getPostType() {
  return postType;
 }

 public void setPostType(PostTypeRec postType) {
  this.postType = postType;
 }

 public String getReference1() {
  return reference1;
 }

 public void setReference1(String reference1) {
  this.reference1 = reference1;
 }

 public String getReference2() {
  return reference2;
 }

 public void setReference2(String reference2) {
  this.reference2 = reference2;
 }

 public boolean isAutoGenerated() {
  return autoGenerated;
 }

 public void setAutoGenerated(boolean autoGenerated) {
  this.autoGenerated = autoGenerated;
 }

 public VatCodeCompanyRec getVatCode() {
  return vatCode;
 }

 public void setVatCode(VatCodeCompanyRec vatCode) {
  this.vatCode = vatCode;
 }

 public List<DocLineBasePartialRec> getClearingLineForLines() {
  return clearingLineForLines;
 }

 public void setClearingLineForLines(List<DocLineBasePartialRec> clearingLineForLines) {
  this.clearingLineForLines = clearingLineForLines;
 }

 public DocLineBasePartialRec getClearedByLine() {
  return clearedByLine;
 }

 public void setClearedByLine(DocLineBasePartialRec clearedByLine) {
  this.clearedByLine = clearedByLine;
 }

 public boolean isClearedLine() {
  return clearedLine;
 }

 public void setClearedLine(boolean clearedLine) {
  this.clearedLine = clearedLine;
 }

 public boolean isClearingLine() {
  return clearingLine;
 }

 public void setClearingLine(boolean clearingLine) {
  this.clearingLine = clearingLine;
 }

 public Date getClearingDate() {
  return clearingDate;
 }

 public void setClearingDate(Date clearingDate) {
  this.clearingDate = clearingDate;
 }

 public CompanyBasicRec getComp() {
  return comp;
 }

 public void setComp(CompanyBasicRec comp) {
  this.comp = comp;
 }

 
    
}
