/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rationem.busRec.doc;

import com.rationem.busRec.config.common.LineTypeRuleRec;
import com.rationem.busRec.config.company.PostTypeRec;
import com.rationem.busRec.fi.company.CompanyBasicRec;
import com.rationem.busRec.tr.BnkPaymentRunRec;
import com.rationem.busRec.user.UserRec;
import com.rationem.busRec.salesTax.vat.VatCodeCompanyRec;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;




/**
 * Document line base class to be over ridden by the actual line type GL,AR,AP,BNK
 * @author Chris
 */
public  class DocLineBaseRec  implements Serializable{
 private static final Logger LOGGER =  Logger.getLogger(DocLineBaseRec.class.getName());
    private Long id;
    private Long docNumber;
    private Long lineNum;
    private Date createDate;
    private UserRec createBy;
    private Date changeDate;
    private UserRec changeBy;
    private int revision;
    private String accountRef;
    //private String docCurrCode;
    private double docAmount;
    private String docAmountStr;
    private double homeAmount;
    private double orginalAmount;
    private double paidAmount;
    private String lineText;
    private String sortOrder;
    private String debitValue;
    private String creditValue;
    private boolean reset;

    private DocBaseRec docHeaderBase;
    //LineTypeRule
    private LineTypeRuleRec lineType;
    /**
     * Posting type e.g. GL DR/CR
     */
    private PostTypeRec postType;
    /**
     * User reference 1
     */
    private String reference1;
    /**
     * User Reference 2
     */
    private String reference2;
    
    private String notes;
    private boolean autoGenerated;
    private double taxAmnt;
    private List<DocLineBaseRec> clearingLineForLines;
    /**
     * Document line that clears this document line
     */
    private DocLineBaseRec clearedByLine;
    private boolean clearedLine;
    private boolean clearingLine;
    private Date clearingDate;
    private CompanyBasicRec comp;
    private DocBankLineBaseRec bankLine;
    private BnkPaymentRunRec bnkPaymentRun;
    private DocLineBaseRec partPaymentLine;



  public DocLineBaseRec() {
  }

  public DocLineBaseRec(Long id, Long lineNum, Date createDate, UserRec createBy,
          Date changeDate, UserRec changeBy, int revision, double homeAmount,
          String lineText, String sortOrder, DocBaseRec docHeaderBase, LineTypeRuleRec lineType) {
    this.id = id;
    this.lineNum = lineNum;
    this.createDate = createDate;
    this.createBy = createBy;
    this.changeDate = changeDate;
    this.changeBy = changeBy;
    this.revision = revision;
    this.homeAmount = homeAmount;
    this.lineText = lineText;
    this.sortOrder = sortOrder;
    this.docHeaderBase = docHeaderBase;
    this.lineType = lineType;
  }

  public UserRec getChangeBy() {
    return changeBy;
  }

  public void setChangeBy(UserRec changeBy) {
    this.changeBy = changeBy;
  }

  public Date getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(Date changeDate) {
    this.changeDate = changeDate;
  }

  public UserRec getCreateBy() {
    return createBy;
  }

  public void setCreateBy(UserRec createBy) {
    this.createBy = createBy;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  
 
 public boolean isAutoGenerated() {
  return autoGenerated;
 }

 public void setAutoGenerated(boolean autoGenerated) {
  this.autoGenerated = autoGenerated;
 }

 public String getAccountRef() {
  return accountRef;
 }

 public void setAccountRef(String accountRef) {
  this.accountRef = accountRef;
 }

 public String getDebitValue() {
  if(debitValue == null || debitValue.equals("0.00")){
   
   return  new String();
  }
  
  return debitValue;
 }

 public void setDebitValue(String debitValue) {
  this.debitValue = debitValue;
 }

 public String getCreditValue() {
  if(creditValue == null || creditValue.equals("0.00")){
   return  new String();
  }
  return creditValue;
 }

 public void setCreditValue(String creditValue) {
  this.creditValue = creditValue;
 }

 
 
 
 public double getDocAmount() {
  return docAmount;
 }

 public void setDocAmount(double docAmount) {
  this.docAmount = docAmount;
 }

 public String getDocAmountStr() {
  return docAmountStr;
 }

 public void setDocAmountStr(String docAmountStr) {
  this.docAmountStr = docAmountStr;
 }

  public DocBaseRec getDocHeaderBase() {
    return docHeaderBase;
  }

  public void setDocHeaderBase(DocBaseRec docHeaderBase) {
    this.docHeaderBase = docHeaderBase;
  }

 public Long getDocNumber() {
  return docNumber;
 }

 public void setDocNumber(Long docNumber) {
  this.docNumber = docNumber;
 }

  
  public double getHomeAmount() {
    return homeAmount;
  }

  public void setHomeAmount(double homeAmount) {
    this.homeAmount = homeAmount;
  }

  public Long getId() {
   return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getLineNum() {
    return lineNum;
  }

  public void setLineNum(Long lineNum) {
    this.lineNum = lineNum;
  }

  public String getLineText() {
    return lineText;
  }

  public void setLineText(String lineText) {
    this.lineText = lineText;
  }

  public LineTypeRuleRec getLineType() {
    return lineType;
  }

  public void setLineType(LineTypeRuleRec lineType) {
    this.lineType = lineType;
  }

 public String getNotes() {
  return notes;
 }

 public void setNotes(String notes) {
  this.notes = notes;
 }

  
 public double getOrginalAmount() {
  return orginalAmount;
 }

 public void setOrginalAmount(double orginalAmount) {
  this.orginalAmount = orginalAmount;
 }

 public double getPaidAmount() {
  return paidAmount;
 }

 public void setPaidAmount(double paidAmount) {
  this.paidAmount = paidAmount;
 }

 public DocLineBaseRec getPartPaymentLine() {
  return partPaymentLine;
 }

 public void setPartPaymentLine(DocLineBaseRec partPaymentLine) {
  this.partPaymentLine = partPaymentLine;
 }

 
  public int getRevision() {
    return revision;
  }

  public void setRevision(int revision) {
    this.revision = revision;
  }

  public String getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
  }

 public double getTaxAmnt() {
  return taxAmnt;
 }

 public void setTaxAmnt(double taxAmnt) {
  this.taxAmnt = taxAmnt;
 }

  
  public PostTypeRec getPostType() {

    if(postType == null){
      postType = new PostTypeRec();
    }
    return postType;
  }

  public void setPostType(PostTypeRec postCode) {
    this.postType = postCode;
  }

 public DocBankLineBaseRec getBankLine() {
  return bankLine;
 }

 public void setBankLine(DocBankLineBaseRec bankLine) {
  this.bankLine = bankLine;
 }

 public BnkPaymentRunRec getBnkPaymentRun() {
  return bnkPaymentRun;
 }

 public void setBnkPaymentRun(BnkPaymentRunRec bnkPaymentRun) {
  this.bnkPaymentRun = bnkPaymentRun;
 }

  
  public DocLineBaseRec getClearedByLine() {
    return clearedByLine;
  }

  public void setClearedByLine(DocLineBaseRec clearedByLine) {
    this.clearedByLine = clearedByLine;
  }

 public Date getClearingDate() {
  return clearingDate;
 }

 public void setClearingDate(Date clearingDate) {
  this.clearingDate = clearingDate;
 }

 public boolean isClearedLine() {
  return clearedLine;
 }

 public void setClearedLine(boolean clearedLine) {
  this.clearedLine = clearedLine;
 }

 public boolean isClearingLine() {
  return clearingLine;
 }

 public void setClearingLine(boolean clearingLine) {
  this.clearingLine = clearingLine;
 }

  public List<DocLineBaseRec> getClearingLineForLines() {
    return clearingLineForLines;
  }

  public void setClearingLineForLines(List<DocLineBaseRec> clearingLineForLines) {
    this.clearingLineForLines = clearingLineForLines;
  }

 public CompanyBasicRec getComp() {
  return comp;
 }

 public void setComp(CompanyBasicRec comp) {
  this.comp = comp;
 }

  public String getReference1() {
    return reference1;
  }

  public void setReference1(String reference1) {
    this.reference1 = reference1;
  }

  public String getReference2() {
    return reference2;
  }

  public void setReference2(String reference2) {
    this.reference2 = reference2;
  }

 public boolean isReset() {
  return reset;
 }

 public void setReset(boolean reset) {
  this.reset = reset;
 }


 
}
